development:
  adapter: postgresql
  encoding: unicode
  database: mystuff_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: mystuff_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: mystuff_production
  pool: 5
  username:
  password:
